[package]
name = "diesel-experiment"
version = "0.1.0"
authors = ["Sam Martin <Nivekkas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
diesel = {version = "*", features = ["sqlite"]}